### ISSUE TITLE
Update baseline Kotlin requirement to Kotlin 1.4

### ISSUE THREAD

**Issue by jvz** [apache/logging-log4j-kotlin#31]
The latest release of Kotlin is 1.8.x, and we only require 1.3.x. Starting in `log4j-api-kotlin` version 1.4.0, this should require Kotlin 1.4.x. Some potentially useful info about the process: https://kotlinlang.org/docs/whatsnew14.html#migrating-to-kotlin-1-4-0

**Comment by rocketraman** [comment]
Closing in favor of https://github.com/apache/logging-log4j-kotlin/issues/42.
