### ISSUE TITLE
catching() is missing in KotlinLogger

### ISSUE THREAD

**Issue by bjmi** [apache/logging-log4j-kotlin#32]
It looks like `Logger.catching(..)` methods are missing in `KotlinLogger`.

If there is an equivalent for that then please mention it in _KDoc_ of `KotlinLogger` and / or at Log4j Kotlin project site.
Fix version `1.2.1` and `1.3` are acceptable.

Previously created at https://issues.apache.org/jira/browse/LOG4J2-3649

**Comment by jvz** [comment]
Thanks for the report! I'll make sure this is included in the upcoming 1.3.0 release (1.2.1 will be skipped because I ended up adding other new APIs which warrants a version bump).
