### ISSUE TITLE
New release supporting #64 ? 

### ISSUE THREAD

**Issue by torfinnberset** [apache/logging-log4j-kotlin#81]
Hi, I was wondering if it was time to do a new release so that we can start using the coroutine improvements introduced in #64 ? Thank you!

**Comment by vy** [comment]
@torfinnberset, I can cut the `1.5.0` release this weekend.

@rocketraman, is there anything else you want to get into the upcoming release?

**Comment by rocketraman** [comment]
> @rocketraman, is there anything else you want to get into the upcoming release?

No, go ahead and release @vy . Thank you.

**Comment by torfinnberset** [comment]
@vy @rocketraman Thank you! Much appreciated

**Comment by vy** [comment]
@torfinnberset, I've drafted the release – now we need to wait for 72 hours for [voting the release](https://lists.apache.org/thread/y77op7zgvv0385ng84pz6c1nglvkzgrg).

**Comment by vy** [comment]
@torfinnberset, Log4j Kotlin API `1.5.0` is released! :partying_face:

**Comment by torfinnberset** [comment]
Thank you! This will hopefully help us streamline some of the extensive logging requirements we have
